[build]
  base    = ""
  publish = "build"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { REACT_APP_API_URL= "https://staging.radio.com", NODE_VERSION = "v10.16.0" }

[context.staging]
  environment = { REACT_APP_API_URL= "https://staging.radio.com", NODE_VERSION = "v10.16.0" }

[context.deploy-preview]
  environment = { REACT_APP_API_URL= "https://staging.radio.com", NODE_VERSION = "v10.16.0" }